<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK0f18Rd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK0f18Rd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK0f18Rd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK0f18Rd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK0f18Rd\App_KernelDevDebugContainer([
    'container.build_hash' => 'K0f18Rd',
    'container.build_id' => '26035b51',
    'container.build_time' => 1681374739,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK0f18Rd');
