<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA0j6FJL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA0j6FJL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA0j6FJL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA0j6FJL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA0j6FJL\App_KernelDevDebugContainer([
    'container.build_hash' => 'A0j6FJL',
    'container.build_id' => 'eb4cbc57',
    'container.build_time' => 1681389729,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA0j6FJL');
